<!-- eslint-disable vue/no-v-html -->
<template>
  <v-container class="o-article">
    <h1>Privacy Policy</h1>

    <p>Last updated: January 10, 2020</p>

    <p>
      This Privacy Policy describes Our policies and procedures on the
      collection, use and disclosure of Your information when You use the
      Service and tells You about Your privacy rights and how the law protects
      You.
    </p>

    <p>
      We use Your Personal data to provide and improve the Service. By using the
      Service, You agree to the collection and use of information in accordance
      with this Privacy Policy.
    </p>

    <h2>Interpretation and Definitions</h2>
    <h3>Interpretation</h3>
    <p>
      The words of which the initial letter is capitalized have meanings defined
      under the following conditions.
    </p>
    <p>
      The following definitions shall have the same meaning regardless of
      whether they appear in singular or in plural.
    </p>

    <h3>Definitions</h3>
    <p>For the purposes of this Privacy Policy:</p>
    <ul>
      <li>
        <p>
          <strong>You</strong> means the individual accessing or using the
          Service, or the company, or other legal entity on behalf of which such
          individual is accessing or using the Service, as applicable.
        </p>
      </li>
      <li>
        <p>
          <strong>Company</strong> (referred to as either "the Company", "We",
          "Us" or "Our" in this Agreement) refers to SARL OUEDKNISS, 346 Parc
          Ben Omar, Kouba, Algiers, 16000.
        </p>
      </li>
      <li>
        <strong>Affiliate</strong> means an entity that controls, is controlled
        by or is under common control with a party, where "control" means
        ownership of 50% or more of the shares, equity interest or other
        securities entitled to vote for election of directors or other managing
        authority.
      </li>
      <li>
        <strong>Account</strong> means a unique account created for You to
        access our Service or parts of our Service.
      </li>
      <li>
        <strong>Website</strong> refers to Ouedkniss, accessible from
        <a href="https://www.ouedkniss.com">
          https://www.ouedkniss.com
        </a>
      </li>
      <li><strong>Service</strong> refers to the Website.</li>
      <li><strong>Country</strong> refers to: Algeria</li>
      <li>
        <p>
          <strong>Service Provider</strong> means any natural or legal person
          who processes the data on behalf of the Company. It refers to
          third-party companies or individuals employed by the Company to
          facilitate the Service, to provide the Service on behalf of the
          Company, to perform services related to the Service or to assist the
          Company in analyzing how the Service is used.
        </p>
      </li>
      <li>
        <strong>Third-party Social Media Service</strong> refers to any website
        or any social network website through which a User can log in or create
        an account to use the Service.
      </li>
      <li>
        <p>
          <strong>Personal Data</strong> is any information that relates to an
          identified or identifiable individual.
        </p>
      </li>
      <li>
        <strong>Cookies</strong> are size="small" files that are placed on Your
        computer, mobile device or any other device by a website, containing the
        details of Your browsing history on that website among its many uses.
      </li>
      <li>
        <strong>Usage Data</strong> refers to data collected automatically,
        either generated by the use of the Service or from the Service
        infrastructure itself (for example, the duration of a page visit).
      </li>
    </ul>

    <h2>Collecting and Using Your Personal Data</h2>
    <h3>Types of Data Collected</h3>

    <h4>Personal Data</h4>
    <p>
      While using Our Service, We may ask You to provide Us with certain
      personally identifiable information that can be used to contact or
      identify You. Personally identifiable information may include, but is not
      limited to:
    </p>
    <ul>
      <li>Email address</li>
      <li>First name and last name</li>
      <li>Phone number</li>
      <li>Address, State, Province, ZIP/Postal code, City</li>
      <li>
        Bank account information in order to pay for products and/or services
        within the Service
      </li>
      <li>Usage Data</li>
    </ul>

    <p>
      When You pay for a product and/or a service via bank transfer, We may ask
      You to provide information to facilitate this transaction and to verify
      Your identity. Such information may include, without limitation:
    </p>
    <ul>
      <li>Date of birth</li>
      <li>Passport or National ID card</li>
      <li>Bank card statement</li>
      <li>Other information linking You to an address</li>
    </ul>

    <h4>Usage Data</h4>
    <p>Usage Data is collected automatically when using the Service.</p>
    <p>
      Usage Data may include information such as Your Device's Internet Protocol
      address (e.g. IP address), browser type, browser version, the pages of our
      Service that You visit, the time and date of Your visit, the time spent on
      those pages, unique device identifiers and other diagnostic data.
    </p>
    <p>
      When You access the Service by or through a mobile device, We may collect
      certain information automatically, including, but not limited to, the type
      of mobile device You use, Your mobile device unique ID, the IP address of
      Your mobile device, Your mobile operating system, the type of mobile
      Internet browser You use, unique device identifiers and other diagnostic
      data.
    </p>
    <p>
      We may also collect information that Your browser sends whenever You visit
      our Service or when You access the Service by or through a mobile device.
    </p>

    <h4>Information from Third-Party Social Media Services</h4>
    <p>
      The Company allows You to create an account and log in to use the Service
      through the following Third-party Social Media Services:
    </p>
    <ul>
      <li>Google</li>
      <li>Facebook</li>
      <li>Twitter</li>
    </ul>
    <p>
      If You decide to register through or otherwise grant us access to a
      Third-Party Social Media Service, We may collect Personal data that is
      already associated with Your Third-Party Social Media Service's account,
      such as Your name, Your email address, Your activities or Your contact
      list associated with that account.
    </p>
    <p>
      You may also have the option of sharing additional information with the
      Company through Your Third-Party Social Media Service's account. If You
      choose to provide such information and Personal Data, during registration
      or otherwise, You are giving the Company permission to use, share, and
      store it in a manner consistent with this Privacy Policy.
    </p>

    <h4>Tracking Technologies and Cookies</h4>
    <p>
      We use Cookies and similar tracking technologies to track the activity on
      Our Service and store certain information. Tracking technologies used are
      beacons, tags, and scripts to collect and track information and to improve
      and analyze Our Service.
    </p>
    <p>
      You can instruct Your browser to refuse all Cookies or to indicate when a
      Cookie is being sent. However, if You do not accept Cookies, You may not
      be able to use some parts of our Service.
    </p>
    <p>
      Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies
      remain on your personal computer or mobile device when You go offline,
      while Session Cookies are deleted as soon as You close your web browser.
    </p>
    <p>
      We use both session and persistent Cookies for the purposes set out below:
    </p>
    <ul>
      <li>
        <p><strong>Necessary / Essential Cookies</strong></p>
        <p>Type: Session Cookies</p>
        <p>Administered by: Us</p>
        <p>
          Purpose: These Cookies are essential to provide You with services
          available through the Website and to enable You to use some of its
          features. They help to authenticate users and prevent fraudulent use
          of user accounts. Without these Cookies, the services that You have
          asked for cannot be provided, and We only use these Cookies to provide
          You with those services.
        </p>
      </li>
      <li>
        <p><strong>Cookies Policy / Notice Acceptance Cookies</strong></p>
        <p>Type: Persistent Cookies</p>
        <p>Administered by: Us</p>
        <p>
          Purpose: These Cookies identify if users have accepted the use of
          cookies on the Website.
        </p>
      </li>
      <li>
        <p><strong>Functionality Cookies</strong></p>
        <p>Type: Persistent Cookies</p>
        <p>Administered by: Us</p>
        <p>
          Purpose: These Cookies allow us to remember choices You make when You
          use the Website, such as remembering your login details or language
          preference. The purpose of these Cookies is to provide You with a more
          personal experience and to avoid You having to re-enter your
          preferences every time You use the Website.
        </p>
      </li>
      <li>
        <p><strong>Tracking and Performance Cookies</strong></p>
        <p>Type: Persistent Cookies</p>
        <p>Administered by: Third-Parties</p>
        <p>
          Purpose: These Cookies are used to track information about traffic to
          the Website and how users use the Website. The information gathered
          via these Cookies may directly or indirectly identify you as an
          individual visitor. This is because the information collected is
          typically linked to a pseudonymous identifier associated with the
          device you use to access the Website. We may also use these Cookies to
          test new advertisements, pages, features or new functionality of the
          Website to see how our users react to them.
        </p>
      </li>
      <li>
        <p><strong>Targeting and Advertising Cookies</strong></p>
        <p>Type: Persistent Cookies</p>
        <p>Administered by: Third-Parties</p>
        <p>
          Purpose: These Cookies track your browsing habits to enable Us to show
          advertising which is more likely to be of interest to You. These
          Cookies use information about your browsing history to group You with
          other users who have similar interests. Based on that information, and
          with Our permission, third party advertisers can place Cookies to
          enable them to show adverts which We think will be relevant to your
          interests while You are on third party websites.
        </p>
      </li>
    </ul>
    <p>
      For more information about the cookies we use and your choices regarding
      cookies, please visit our Cookies Policy.
    </p>

    <h3>Use of Your Personal Data</h3>
    <p>The Company may use Personal Data for the following purposes:</p>
    <ul>
      <li>
        <strong>To provide and maintain our Service</strong>, including to
        monitor the usage of our Service.
      </li>
      <li>
        <strong>To manage Your Account:</strong> to manage Your registration as
        a user of the Service. The Personal Data You provide can give You access
        to different functionalities of the Service that are available to You as
        a registered user.
      </li>
      <li>
        <strong>For the performance of a contract:</strong> the development,
        compliance and undertaking of the purchase contract for the products,
        items or services You have purchased or of any other contract with Us
        through the Service.
      </li>
      <li>
        <strong>To contact You:</strong> To contact You by email, telephone
        calls, SMS, or other equivalent forms of electronic communication, such
        as a mobile application's push notifications regarding updates or
        informative communications related to the functionalities, products or
        contracted services, including the security updates, when necessary or
        reasonable for their implementation.
      </li>
      <li>
        <strong>To provide You</strong> with news, special offers and general
        information about other goods, services and events which we offer that
        are similar to those that you have already purchased or enquired about
        unless You have opted not to receive such information.
      </li>
      <li>
        <strong>To manage Your requests:</strong> To attend and manage Your
        requests to Us.
      </li>
    </ul>

    <p>We may share your personal information in the following situations:</p>

    <ul>
      <li>
        <strong>With Service Providers:</strong> We may share Your personal
        information with Service Providers to monitor and analyze the use of our
        Service, to show advertisements to You to help support and maintain Our
        Service, to contact You, to advertise on third party websites to You
        after You visited our Service or for payment processing.
      </li>
      <li>
        <strong>For Business transfers:</strong> We may share or transfer Your
        personal information in connection with, or during negotiations of, any
        merger, sale of Company assets, financing, or acquisition of all or a
        portion of our business to another company.
      </li>
      <li>
        <strong>With Affiliates:</strong> We may share Your information with Our
        affiliates, in which case we will require those affiliates to honor this
        Privacy Policy. Affiliates include Our parent company and any other
        subsidiaries, joint venture partners or other companies that We control
        or that are under common control with Us.
      </li>
      <li>
        <strong>With Business partners:</strong> We may share Your information
        with Our business partners to offer You certain products, services or
        promotions.
      </li>
      <li>
        <strong>With other users:</strong> when You share personal information
        or otherwise interact in the public areas with other users, such
        information may be viewed by all users and may be publicly distributed
        outside. If You interact with other users or register through a
        Third-Party Social Media Service, Your contacts on the Third-Party
        Social Media Service may see You name, profile, pictures and description
        of Your activity. Similarly, other users will be able to view
        descriptions of Your activity, communicate with You and view Your
        profile.
      </li>
    </ul>

    <h3>Retention of Your Personal Data</h3>
    <p>
      The Company will retain Your Personal Data only for as long as is
      necessary for the purposes set out in this Privacy Policy. We will retain
      and use Your Personal Data to the extent necessary to comply with our
      legal obligations (for example, if we are required to retain your data to
      comply with applicable laws), resolve disputes, and enforce our legal
      agreements and policies.
    </p>
    <p>
      The Company will also retain Usage Data for internal analysis purposes.
      Usage Data is generally retained for a shorter period of time, except when
      this data is used to strengthen the security or to improve the
      functionality of Our Service, or We are legally obligated to retain this
      data for longer time periods.
    </p>

    <h3>Transfer of Your Personal Data</h3>
    <p>
      Your information, including Personal Data, is processed at the Company's
      operating offices and in any other places where the parties involved in
      the processing are located. It means that this information may be
      transferred to — and maintained on — computers located outside of Your
      state, province, country or other governmental jurisdiction where the data
      protection laws may differ than those from Your jurisdiction.
    </p>
    <p>
      Your consent to this Privacy Policy followed by Your submission of such
      information represents Your agreement to that transfer.
    </p>
    <p>
      The Company will take all steps reasonably necessary to ensure that Your
      data is treated securely and in accordance with this Privacy Policy and no
      transfer of Your Personal Data will take place to an organization or a
      country unless there are adequate controls in place including the security
      of Your data and other personal information.
    </p>

    <h3>Disclosure of Your Personal Data</h3>
    <h4>Business Transactions</h4>
    <p>
      If the Company is involved in a merger, acquisition or asset sale, Your
      Personal Data may be transferred. We will provide notice before Your
      Personal Data is transferred and becomes subject to a different Privacy
      Policy.
    </p>
    <h4>Law enforcement</h4>
    <p>
      Under certain circumstances, the Company may be required to disclose Your
      Personal Data if required to do so by law or in response to valid requests
      by public authorities (e.g. a court or a government agency).
    </p>
    <h4>Other legal requirements</h4>
    <p>
      The Company may disclose Your Personal Data in the good faith belief that
      such action is necessary to:
    </p>
    <ul>
      <li>Comply with a legal obligation</li>
      <li>Protect and defend the rights or property of the Company</li>
      <li>
        Prevent or investigate possible wrongdoing in connection with the
        Service
      </li>
      <li>Protect the personal safety of Users of the Service or the public</li>
      <li>Protect against legal liability</li>
    </ul>

    <h3>Security of Your Personal Data</h3>
    <p>
      The security of Your Personal Data is important to Us, but remember that
      no method of transmission over the Internet, or method of electronic
      storage is 100% secure. While We strive to use commercially acceptable
      means to protect Your Personal Data, We cannot guarantee its absolute
      security.
    </p>

    <h2>Detailed Information on the Processing of Your Personal Data</h2>
    <p>
      Service Providers have access to Your Personal Data only to perform their
      tasks on Our behalf and are obligated not to disclose or use it for any
      other purpose.
    </p>

    <h3>Analytics</h3>
    <p>
      We may use third-party Service providers to monitor and analyze the use of
      our Service.
    </p>
    <ul>
      <li>
        <p><strong>Google Analytics</strong></p>
        <p>
          Google Analytics is a web analytics service offered by Google that
          tracks and reports website traffic. Google uses the data collected to
          track and monitor the use of our Service. This data is shared with
          other Google services. Google may use the collected data to
          contextualise and personalise the ads of its own advertising network.
        </p>
        <p>
          You can opt-out of having made your activity on the Service available
          to Google Analytics by installing the Google Analytics opt-out browser
          add-on. The add-on prevents the Google Analytics JavaScript (ga.js,
          analytics.js and dc.js) from sharing information with Google Analytics
          about visits activity.
        </p>
        <p>
          For more information on the privacy practices of Google, please visit
          the Google Privacy &amp; Terms web page:
          <a
            href="https://policies.google.com/privacy?hl=en"
            v-html="formatUrl('https://policies.google.com/privacy?hl=en')"
          ></a>
        </p>
      </li>
      <li>
        <p><strong>Matomo</strong></p>
        <p>
          Matomo is a web analytics service. You can visit their Privacy Policy
          page here:
          <a
            href="https://matomo.org/privacy-policy"
            v-html="formatUrl('https://matomo.org/privacy-policy')"
          ></a>
        </p>
      </li>
    </ul>

    <h3>Advertising</h3>
    <p>
      We may use Service providers to show advertisements to You to help support
      and maintain Our Service.
    </p>
    <ul>
      <li>
        <p><strong>Google AdSense &amp; DoubleClick Cookie</strong></p>
        <p>
          Google, as a third party vendor, uses cookies to serve ads on our
          Service. Google's use of the DoubleClick cookie enables it and its
          partners to serve ads to our users based on their visit to our Service
          or other websites on the Internet.
        </p>
        <p>
          You may opt out of the use of the DoubleClick Cookie for
          interest-based advertising by visiting the Google Ads Settings web
          page:
          <a
            href="http://www.google.com/ads/preferences/"
            v-html="formatUrl('http://www.google.com/ads/preferences/')"
          ></a>
        </p>
      </li>
    </ul>

    <h3>Email Marketing</h3>
    <p>
      We may use Your Personal Data to contact You with newsletters, marketing
      or promotional materials and other information that may be of interest to
      You. You may opt-out of receiving any, or all, of these communications
      from Us by following the unsubscribe link or instructions provided in any
      email We send or by contacting Us.
    </p>
    <p>
      We may use Email Marketing Service Providers to manage and send emails to
      You.
    </p>

    <h3>Behavioral Remarketing</h3>
    <p>
      The Company uses remarketing services to advertise on third party websites
      to You after You visited our Service. We and Our third-party vendors use
      cookies to inform, optimize and serve ads based on Your past visits to our
      Service.
    </p>
    <ul>
      <li>
        <p><strong>Facebook</strong></p>
        <p>Facebook remarketing service is provided by Facebook Inc.</p>
        <p>
          You can learn more about interest-based advertising from Facebook by
          visiting this page:
          <a
            href="https://www.facebook.com/help/164968693837950"
            v-html="formatUrl('https://www.facebook.com/help/164968693837950')"
          ></a>
        </p>
        <p>
          To opt-out from Facebook's interest-based ads, follow these
          instructions from Facebook:
          <a
            href="https://www.facebook.com/help/568137493302217"
            v-html="formatUrl('https://www.facebook.com/help/568137493302217')"
          ></a>
        </p>
        <p></p>
        <p>
          Facebook adheres to the Self-Regulatory Principles for Online
          Behavioural Advertising established by the Digital Advertising
          Alliance. You can also opt-out from Facebook and other participating
          companies through the Digital Advertising Alliance in the USA
          <a
            href="http://www.aboutads.info/choices/"
            v-html="formatUrl('http://www.aboutads.info/choices/')"
          ></a
          >, the Digital Advertising Alliance of Canada in Canada
          <a href="http://youradchoices.ca/">http://youradchoices.ca/</a> or the
          European Interactive Digital Advertising Alliance in Europe
          <a href="http://www.youronlinechoices.eu/"
            >http://www.youronlinechoices.eu/</a
          >, or opt-out using your mobile device settings.
        </p>
        <p>
          For more information on the privacy practices of Facebook, please
          visit Facebook's Data Policy:
          <a
            href="https://www.facebook.com/privacy/explanation"
            v-html="formatUrl('https://www.facebook.com/privacy/explanation')"
          ></a>
        </p>
      </li>
    </ul>

    <h3>Payments</h3>
    <p>
      We may provide paid products and/or services within the Service. In that
      case, we may use third-party services for payment processing (e.g. payment
      processors).
    </p>
    <p>
      We will not store or collect Your payment card details. That information
      is provided directly to Our third-party payment processors whose use of
      Your personal information is governed by their Privacy Policy. These
      payment processors adhere to the standards set by PCI-DSS as managed by
      the PCI Security Standards Council, which is a joint effort of brands like
      Visa, Mastercard, American Express and Discover. PCI-DSS requirements help
      ensure the secure handling of payment information.
    </p>
    <ul></ul>

    <p>
      When You use Our Service to pay a product and/or service via bank
      transfer, We may ask You to provide information to facilitate this
      transaction and to verify Your identity.
    </p>

    <h2>Children's Privacy</h2>
    <p>
      The Service may contain content appropriate for children under the age of
      13. As a parent, you should know that through the Service children under
      the age of 13 may participate in activities that involve the collection or
      use of personal information. We use reasonable efforts to ensure that
      before we collect any personal information from a child, the child's
      parent receives notice of and consents to our personal information
      practices.
    </p>
    <p>
      We also may limit how We collect, use, and store some of the information
      of Users between 13 and 18 years old. In some cases, this means We will be
      unable to provide certain functionality of the Service to these Users. If
      We need to rely on consent as a legal basis for processing Your
      information and Your country requires consent from a parent, We may
      require Your parent's consent before We collect and use that information.
    </p>
    <p>
      We may ask a User to verify its date of birth before collecting any
      personal information from them. If the User is under the age of 13, the
      Service will be either blocked or redirected to a parental consent
      process.
    </p>

    <h3>Information Collected from Children Under the Age of 13</h3>
    <p>
      The Company may collect and store persistent identifiers such as cookies
      or IP addresses from Children without parental consent for the purpose of
      supporting the internal operation of the Service.
    </p>
    <p>
      We may collect and store other personal information about children if this
      information is submitted by a child with prior parent consent or by the
      parent or guardian of the child.
    </p>
    <p>
      The Company may collect and store the following types of personal
      information about a child when submitted by a child with prior parental
      consent or by the parent or guardian of the child:
    </p>
    <ul>
      <li>First and/or last name</li>
      <li>Date of birth</li>
      <li>Gender</li>
      <li>Grade level</li>
      <li>Email address</li>
      <li>Telephone number</li>
      <li>Parent's or guardian's name</li>
      <li>Parent's or guardian's email address</li>
    </ul>
    <p>
      For further details on the information We might collect, You can refer to
      the "Types of Data Collected" section of this Privacy Policy. We follow
      our standard Privacy Policy for the disclosure of personal information
      collected from and about children.
    </p>

    <h3>Parental Access</h3>
    <p>
      A parent who has already given the Company permission to collect and use
      his child personal information can, at any time:
    </p>
    <ul>
      <li>Review, correct or delete the child's personal information</li>
      <li>
        Discontinue further collection or use of the child's personal
        information
      </li>
    </ul>
    <p>
      To make such a request, You can write to Us using the contact information
      provided in this Privacy Policy.
    </p>

    <h2>
      Your California Privacy Rights (California Business and Professions Code
      Section 22581)
    </h2>
    <p>
      California Business and Professions Code section 22581 allow California
      residents under the age of 18 who are registered users of online sites,
      services or applications to request and obtain removal of content or
      information they have publicly posted.
    </p>
    <p>
      To request removal of such data, and if you are a California resident, You
      can contact Us using the contact information provided below, and include
      the email address associated with Your account.
    </p>
    <p>
      Be aware that Your request does not guarantee complete or comprehensive
      removal of content or information posted online and that the law may not
      permit or require removal in certain circumstances.
    </p>

    <h2>Links to Other Websites</h2>
    <p>
      Our Service may contain links to other websites that are not operated by
      Us. If You click on a third party link, You will be directed to that third
      party's site. We strongly advise You to review the Privacy Policy of every
      site You visit.
    </p>
    <p>
      We have no control over and assume no responsibility for the content,
      privacy policies or practices of any third party sites or services.
    </p>

    <h2>Changes to this Privacy Policy</h2>
    <p>
      We may update our Privacy Policy from time to time. We will notify You of
      any changes by posting the new Privacy Policy on this page.
    </p>
    <p>
      We will let You know via email and/or a prominent notice on Our Service,
      prior to the change becoming effective and update the "Last updated" date
      at the top of this Privacy Policy.
    </p>
    <p>
      You are advised to review this Privacy Policy periodically for any
      changes. Changes to this Privacy Policy are effective when they are posted
      on this page.
    </p>

    <h2>Contact Us</h2>
    <p>
      If you have any questions about this Privacy Policy, You can contact us:
    </p>
    <ul>
      <li>By email: privacy@ouedkniss.com</li>
      <li>
        By visiting this page on our website:
        <a href="https://www.ouedkniss.com/contact"
          >https://www.ouedkniss.com/contact</a
        >
      </li>
      <li>By phone number: +213777001100</li>
      <li>By mail: 346, Parc Ben Omar, Kouba, Algiers, 16000, Algeria</li>
    </ul>
  </v-container>
</template>

<script>
export default {
  methods: {
    formatUrl(url) {
      var doubleSlash = url.split("//");

      var formatted = doubleSlash
        .map(str =>
          str
            .replace(/(?<after>:)/giu, "$1<wbr>")
            .replace(/(?<before>[/~.,\-_?#%])/giu, "<wbr>$1")
            .replace(/(?<beforeAndAfter>[=&])/giu, "<wbr>$1<wbr>")
        )
        .join("//<wbr>");

      return formatted;
    }
  }
};
</script>
<style scoped>
h2 {
  color: #e95903;
}
h3 {
  color: #4285f4;
}
</style>
