.build:
  extends: .get_version
  stage: build
  image:
    name: $IMAGE_REGISTRY/$IMAGE_BUILDER_TAG
    entrypoint: [""]
  cache:
    key:
      files:
        - yarn.lock
    paths:
        - node_modules
  script:
    - >
      /kaniko/executor --context $CI_PROJECT_DIR 
      --cache=false
      --use-new-run
      --single-snapshot
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --build-arg VUE_APP_GRAPHQL_HTTP=$VUE_APP_GRAPHQL_HTTP
      --build-arg VUE_APP_BRANCH_NAME=$VUE_APP_BRANCH_NAME
      --build-arg VUE_APP_SOCKET_IO=$VUE_APP_SOCKET_IO
      --build-arg VUE_APP_UPLOAD=$VUE_APP_UPLOAD
      --build-arg VUE_APP_OUEDKNISS_AUTH=$VUE_APP_OUEDKNISS_AUTH
      --build-arg VUE_APP_OUEDKNISS_INTEL=$VUE_APP_OUEDKNISS_INTEL
      --build-arg VUE_APP_OUEDKNISS_PANEL=$VUE_APP_OUEDKNISS_PANEL
      --build-arg VUE_APP_OUEDKNISS_PORTAL=$VUE_APP_OUEDKNISS_PORTAL
      --build-arg VUE_APP_OUEDKNISS_STORE=$VUE_APP_OUEDKNISS_STORE
      --build-arg VUE_APP_OUEDKNISS_MARKET=$VUE_APP_OUEDKNISS_MARKET
      --build-arg VUE_APP_OUEDKNISS_DJEZZY=$VUE_APP_OUEDKNISS_DJEZZY
      --build-arg VUE_APP_RECAPTCHA_KEY=$VUE_APP_RECAPTCHA_KEY
      --build-arg VUE_APP_INVISIBLE_RECAPTCHA_KEY=$VUE_APP_RECAPTCHA_INVISIBLE_KEY
      --build-arg VUE_APP_DISABLE_MESSENGER=$VUE_APP_DISABLE_MESSENGER
      --build-arg VUE_APP_DISABLE_OKPIXEL=$VUE_APP_DISABLE_OKPIXEL
      --build-arg VUE_APP_GOOGLE_MAPS_KEY=$VUE_APP_GOOGLE_MAPS_KEY
      --build-arg VUE_APP_GOOGLE_ANALYTICS_4_KEY=$VUE_APP_GOOGLE_ANALYTICS_4_KEY
      --build-arg VUE_APP_GOOGLE_ANALYTICS_SECRET_CODE=$VUE_APP_GOOGLE_ANALYTICS_SECRET_CODE
      --build-arg VUE_APP_FIREBASE_CONFIG=$VUE_APP_FIREBASE_CONFIG
      --build-arg VUE_APP_STATS_API=$VUE_APP_STATS_API
      --build-arg VUE_APP_PIXEL_API=$VUE_APP_PIXEL_API
      --build-arg VUE_APP_SHOW_CUSTOM_ADS=$VUE_APP_SHOW_CUSTOM_ADS
      --build-arg VUE_APP_OKAPTCHA_API=$VUE_APP_OKAPTCHA_API
      --build-arg VUE_APP_OUEDKNISS_CDN=$CDN_URL
      --build-arg VUE_APP_ASSETS_PUBLIC_PATH=$VUE_APP_ASSETS_PUBLIC_PATH
      --build-arg NODE_ENV=$NODE_ENV
      --destination $IMAGE_REGISTRY/$CI_PROJECT_PATH:$IMAGE_TAG
  tags:
    - build

dev:build:
  extends: .build
  resource_group: dev
  variables:
    VUE_APP_GRAPHQL_HTTP: $DEV_VUE_APP_GRAPHQL_HTTP
    VUE_APP_BRANCH_NAME: $CI_COMMIT_REF_NAME
    VUE_APP_SOCKET_IO: $DEV_VUE_APP_SOCKET_IO
    VUE_APP_UPLOAD: $DEV_VUE_APP_STORAGE_URL
    VUE_APP_OUEDKNISS_AUTH: $DEV_VUE_APP_OUEDKNISS_AUTH
    VUE_APP_OUEDKNISS_INTEL: $DEV_VUE_APP_OUEDKNISS_INTEL
    VUE_APP_OUEDKNISS_PANEL: $DEV_VUE_APP_OUEDKNISS_PANEL
    VUE_APP_OUEDKNISS_PORTAL: $DEV_VUE_APP_OUEDKNISS_PORTAL
    VUE_APP_OUEDKNISS_STORE: $DEV_VUE_APP_OUEDKNISS_STORE
    VUE_APP_OUEDKNISS_MARKET: $DEV_VUE_APP_OUEDKNISS_MARKET
    VUE_APP_OUEDKNISS_DJEZZY: $DEV_VUE_APP_OUEDKNISS_DJEZZY
    VUE_APP_RECAPTCHA_KEY: $DEV_RECAPTCHA_SITE_KEY
    VUE_APP_INVISIBLE_RECAPTCHA_KEY: $DEV_VUE_APP_RECAPTCHA_INVISIBLE_KEY
    VUE_APP_DISABLE_MESSENGER: $DEV_VUE_APP_DISABLE_MESSENGER
    VUE_APP_DISABLE_OKPIXEL: $DEV_VUE_APP_DISABLE_OKPIXEL
    VUE_APP_GOOGLE_MAPS_KEY: $DEV_GOOGLE_MAPS_KEY
    VUE_APP_GOOGLE_ANALYTICS_4_KEY: $DEV_GOOGLE_ANALYTICS_4_KEY
    VUE_APP_GOOGLE_ANALYTICS_SECRET_CODE: $DEV_GOOGLE_ANALYTICS_SECRET_CODE
    VUE_APP_FIREBASE_CONFIG: $DEV_VUE_APP_FIREBASE_CONFIG
    VUE_APP_STATS_API: $DEV_VUE_APP_STATS_API
    VUE_APP_PIXEL_API: $DEV_VUE_APP_PIXEL_API
    VUE_APP_SHOW_CUSTOM_ADS: $DEV_VUE_APP_SHOW_CUSTOM_ADS
    VUE_APP_OKAPTCHA_API: $DEV_VUE_APP_OKAPTCHA_API
    VUE_APP_OUEDKNISS_CDN: $DEV_CDN_URL
    VUE_APP_ASSETS_PUBLIC_PATH: $DEV_VUE_APP_ASSETS_PUBLIC_PATH
    IMAGE_TAG: $CI_COMMIT_REF_NAME
    NODE_ENV: development
  only:
    - dev

testing:build:
  extends: .build
  resource_group: testing
  variables:
    VUE_APP_GRAPHQL_HTTP: $DEV_VUE_APP_GRAPHQL_HTTP
    VUE_APP_BRANCH_NAME: $CI_COMMIT_REF_NAME
    VUE_APP_SOCKET_IO: $DEV_VUE_APP_SOCKET_IO
    VUE_APP_UPLOAD: $DEV_VUE_APP_STORAGE_URL
    VUE_APP_OUEDKNISS_AUTH: $TESTING_VUE_APP_OUEDKNISS_AUTH
    VUE_APP_OUEDKNISS_INTEL: $TESTING_VUE_APP_OUEDKNISS_INTEL
    VUE_APP_OUEDKNISS_PANEL: $TESTING_VUE_APP_OUEDKNISS_PANEL
    VUE_APP_OUEDKNISS_PORTAL: $TESTING_VUE_APP_OUEDKNISS_PORTAL
    VUE_APP_OUEDKNISS_STORE: $TESTING_VUE_APP_OUEDKNISS_STORE
    VUE_APP_OUEDKNISS_MARKET: $TESTING_VUE_APP_OUEDKNISS_MARKET
    VUE_APP_OUEDKNISS_DJEZZY: $TESTING_VUE_APP_OUEDKNISS_DJEZZY
    VUE_APP_RECAPTCHA_KEY: $DEV_RECAPTCHA_SITE_KEY
    VUE_APP_INVISIBLE_RECAPTCHA_KEY: $DEV_VUE_APP_RECAPTCHA_INVISIBLE_KEY
    VUE_APP_DISABLE_MESSENGER: $DEV_VUE_APP_DISABLE_MESSENGER
    VUE_APP_DISABLE_OKPIXEL: $DEV_VUE_APP_DISABLE_OKPIXEL
    VUE_APP_GOOGLE_MAPS_KEY: $DEV_GOOGLE_MAPS_KEY
    VUE_APP_GOOGLE_ANALYTICS_4_KEY: $DEV_GOOGLE_ANALYTICS_4_KEY
    VUE_APP_GOOGLE_ANALYTICS_SECRET_CODE: $DEV_GOOGLE_ANALYTICS_SECRET_CODE
    VUE_APP_FIREBASE_CONFIG: $DEV_VUE_APP_FIREBASE_CONFIG
    VUE_APP_STATS_API: $DEV_VUE_APP_STATS_API
    VUE_APP_PIXEL_API: $DEV_VUE_APP_PIXEL_API
    VUE_APP_SHOW_CUSTOM_ADS: $DEV_VUE_APP_SHOW_CUSTOM_ADS
    VUE_APP_OKAPTCHA_API: $DEV_VUE_APP_OKAPTCHA_API
    VUE_APP_OUEDKNISS_CDN: $DEV_CDN_URL
    VUE_APP_ASSETS_PUBLIC_PATH: $DEV_VUE_APP_ASSETS_PUBLIC_PATH
    IMAGE_TAG: testing
    NODE_ENV: development
  except:
    - dev
    - staging
    - master
  when: manual

staging:build:
  extends: .build
  resource_group: staging
  variables:
    VUE_APP_GRAPHQL_HTTP: $DEV_VUE_APP_GRAPHQL_HTTP
    VUE_APP_BRANCH_NAME: $CI_COMMIT_REF_NAME
    VUE_APP_SOCKET_IO: $DEV_VUE_APP_SOCKET_IO
    VUE_APP_UPLOAD: $DEV_VUE_APP_STORAGE_URL
    VUE_APP_OUEDKNISS_AUTH: $STAGING_VUE_APP_OUEDKNISS_AUTH
    VUE_APP_OUEDKNISS_INTEL: $STAGING_VUE_APP_OUEDKNISS_INTEL
    VUE_APP_OUEDKNISS_PANEL: $STAGING_VUE_APP_OUEDKNISS_PANEL
    VUE_APP_OUEDKNISS_PORTAL: $STAGING_VUE_APP_OUEDKNISS_PORTAL
    VUE_APP_OUEDKNISS_STORE: $STAGING_VUE_APP_OUEDKNISS_STORE
    VUE_APP_OUEDKNISS_MARKET: $STAGING_VUE_APP_OUEDKNISS_MARKET
    VUE_APP_OUEDKNISS_DJEZZY: $STAGING_VUE_APP_OUEDKNISS_DJEZZY
    VUE_APP_RECAPTCHA_KEY: $DEV_RECAPTCHA_SITE_KEY
    VUE_APP_INVISIBLE_RECAPTCHA_KEY: $DEV_VUE_APP_RECAPTCHA_INVISIBLE_KEY
    VUE_APP_DISABLE_MESSENGER: $DEV_VUE_APP_DISABLE_MESSENGER
    VUE_APP_DISABLE_OKPIXEL: $DEV_VUE_APP_DISABLE_OKPIXEL
    VUE_APP_GOOGLE_MAPS_KEY: $DEV_GOOGLE_MAPS_KEY
    VUE_APP_GOOGLE_ANALYTICS_4_KEY: $DEV_GOOGLE_ANALYTICS_4_KEY
    VUE_APP_GOOGLE_ANALYTICS_SECRET_CODE: $DEV_GOOGLE_ANALYTICS_SECRET_CODE
    VUE_APP_FIREBASE_CONFIG: $DEV_VUE_APP_FIREBASE_CONFIG
    VUE_APP_STATS_API: $DEV_VUE_APP_STATS_API
    VUE_APP_PIXEL_API: $DEV_VUE_APP_PIXEL_API
    VUE_APP_SHOW_CUSTOM_ADS: $DEV_VUE_APP_SHOW_CUSTOM_ADS
    VUE_APP_OKAPTCHA_API: $DEV_VUE_APP_OKAPTCHA_API
    VUE_APP_OUEDKNISS_CDN: $DEV_CDN_URL
    VUE_APP_ASSETS_PUBLIC_PATH: $DEV_VUE_APP_ASSETS_PUBLIC_PATH
    IMAGE_TAG: $CI_COMMIT_REF_NAME
    NODE_ENV: production
  only:
    - staging

djezzy:build:
  extends: .build
  resource_group: djezzy
  variables:
    VUE_APP_BRANCH_NAME: ""
    VUE_APP_GRAPHQL_HTTP: $PROD_VUE_APP_GRAPHQL_HTTP
    VUE_APP_SOCKET_IO: $PROD_VUE_APP_SOCKET_IO
    VUE_APP_UPLOAD: $PROD_VUE_APP_STORAGE_URL
    VUE_APP_OUEDKNISS_AUTH: $PROD_VUE_APP_OUEDKNISS_AUTH
    VUE_APP_OUEDKNISS_INTEL: $PROD_VUE_APP_OUEDKNISS_INTEL
    VUE_APP_OUEDKNISS_PANEL: $PROD_VUE_APP_OUEDKNISS_PANEL
    VUE_APP_OUEDKNISS_PORTAL: "https://djezzyfront.ouedkniss.com"
    VUE_APP_OUEDKNISS_DJEZZY: $PROD_VUE_APP_OUEDKNISS_DJEZZY
    VUE_APP_OUEDKNISS_STORE: $PROD_VUE_APP_OUEDKNISS_STORE
    VUE_APP_OUEDKNISS_MARKET: $PROD_VUE_APP_OUEDKNISS_MARKET
    VUE_APP_RECAPTCHA_KEY: $PROD_VUE_APP_RECAPTCHA_KEY
    VUE_APP_INVISIBLE_RECAPTCHA_KEY: $PROD_VUE_APP_RECAPTCHA_INVISIBLE_KEY
    VUE_APP_DISABLE_MESSENGER: $PROD_VUE_APP_DISABLE_MESSENGER
    VUE_APP_DISABLE_OKPIXEL: $PROD_VUE_APP_DISABLE_OKPIXEL
    VUE_APP_GOOGLE_MAPS_KEY: $PROD_GOOGLE_MAPS_KEY
    VUE_APP_GOOGLE_ANALYTICS_4_KEY: $PROD_GOOGLE_ANALYTICS_4_KEY
    VUE_APP_GOOGLE_ANALYTICS_SECRET_CODE: $PROD_GOOGLE_ANALYTICS_SECRET_CODE
    VUE_APP_FIREBASE_CONFIG: $PROD_VUE_APP_FIREBASE_CONFIG
    VUE_APP_STATS_API: $PROD_VUE_APP_STATS_API
    VUE_APP_PIXEL_API: $PROD_VUE_APP_PIXEL_API
    VUE_APP_SHOW_CUSTOM_ADS: $PROD_VUE_APP_SHOW_CUSTOM_ADS
    VUE_APP_OKAPTCHA_API: $PROD_VUE_APP_OKAPTCHA_API
    VUE_APP_OUEDKNISS_CDN: $PROD_CDN_URL
    VUE_APP_ASSETS_PUBLIC_PATH: $PROD_VUE_APP_ASSETS_PUBLIC_PATH
    IMAGE_TAG: djezzy
    NODE_ENV: production
  only:
    - djezzy
  tags:
    - build

prod:build:
  extends: .build
  resource_group: production
  variables:
    VUE_APP_BRANCH_NAME: ""
    VUE_APP_GRAPHQL_HTTP: $PROD_VUE_APP_GRAPHQL_HTTP
    VUE_APP_SOCKET_IO: $PROD_VUE_APP_SOCKET_IO
    VUE_APP_UPLOAD: $PROD_VUE_APP_STORAGE_URL
    VUE_APP_OUEDKNISS_AUTH: $PROD_VUE_APP_OUEDKNISS_AUTH
    VUE_APP_OUEDKNISS_INTEL: $PROD_VUE_APP_OUEDKNISS_INTEL
    VUE_APP_OUEDKNISS_PANEL: $PROD_VUE_APP_OUEDKNISS_PANEL
    VUE_APP_OUEDKNISS_PORTAL: $PROD_VUE_APP_OUEDKNISS_PORTAL
    VUE_APP_OUEDKNISS_STORE: $PROD_VUE_APP_OUEDKNISS_STORE
    VUE_APP_OUEDKNISS_MARKET: $PROD_VUE_APP_OUEDKNISS_MARKET
    VUE_APP_OUEDKNISS_DJEZZY: $PROD_VUE_APP_OUEDKNISS_DJEZZY
    VUE_APP_RECAPTCHA_KEY: $PROD_VUE_APP_RECAPTCHA_KEY
    VUE_APP_INVISIBLE_RECAPTCHA_KEY: $PROD_VUE_APP_RECAPTCHA_INVISIBLE_KEY
    VUE_APP_DISABLE_MESSENGER: $PROD_VUE_APP_DISABLE_MESSENGER
    VUE_APP_DISABLE_OKPIXEL: $PROD_VUE_APP_DISABLE_OKPIXEL
    VUE_APP_GOOGLE_MAPS_KEY: $PROD_GOOGLE_MAPS_KEY
    VUE_APP_GOOGLE_ANALYTICS_4_KEY: $PROD_GOOGLE_ANALYTICS_4_KEY
    VUE_APP_GOOGLE_ANALYTICS_SECRET_CODE: $PROD_GOOGLE_ANALYTICS_SECRET_CODE
    VUE_APP_FIREBASE_CONFIG: $PROD_VUE_APP_FIREBASE_CONFIG
    VUE_APP_STATS_API: $PROD_VUE_APP_STATS_API
    VUE_APP_PIXEL_API: $PROD_VUE_APP_PIXEL_API
    VUE_APP_SHOW_CUSTOM_ADS: $PROD_VUE_APP_SHOW_CUSTOM_ADS
    VUE_APP_OKAPTCHA_API: $PROD_VUE_APP_OKAPTCHA_API
    VUE_APP_OUEDKNISS_CDN: $PROD_CDN_URL
    VUE_APP_ASSETS_PUBLIC_PATH: $PROD_VUE_APP_ASSETS_PUBLIC_PATH
    IMAGE_TAG: $CI_COMMIT_REF_NAME
    NODE_ENV: production
  only:
    - master
  tags:
    - k8s_prod
    - prod
 
prod:dz:build:
  extends: .build
  resource_group: production:dz
  variables:
    VUE_APP_BRANCH_NAME: ""
    VUE_APP_GRAPHQL_HTTP: $PROD_VUE_APP_GRAPHQL_HTTP
    VUE_APP_SOCKET_IO: $PROD_DZ_VUE_APP_SOCKET_IO
    VUE_APP_UPLOAD: $PROD_VUE_APP_STORAGE_URL
    VUE_APP_OUEDKNISS_AUTH: $PROD_DZ_VUE_APP_OUEDKNISS_AUTH
    VUE_APP_OUEDKNISS_INTEL: $PROD_DZ_VUE_APP_OUEDKNISS_INTEL
    VUE_APP_OUEDKNISS_PANEL: $PROD_DZ_VUE_APP_OUEDKNISS_PANEL
    VUE_APP_OUEDKNISS_PORTAL: $PROD_DZ_VUE_APP_OUEDKNISS_PORTAL
    VUE_APP_OUEDKNISS_STORE: $PROD_DZ_VUE_APP_OUEDKNISS_STORE
    VUE_APP_OUEDKNISS_MARKET: $PROD_DZ_VUE_APP_OUEDKNISS_MARKET
    VUE_APP_OUEDKNISS_DJEZZY: $PROD_DZ_VUE_APP_OUEDKNISS_DJEZZY
    VUE_APP_RECAPTCHA_KEY: $PROD_VUE_APP_RECAPTCHA_KEY
    VUE_APP_INVISIBLE_RECAPTCHA_KEY: $PROD_VUE_APP_RECAPTCHA_INVISIBLE_KEY
    VUE_APP_DISABLE_MESSENGER: $PROD_VUE_APP_DISABLE_MESSENGER
    VUE_APP_DISABLE_OKPIXEL: $PROD_VUE_APP_DISABLE_OKPIXEL
    VUE_APP_GOOGLE_MAPS_KEY: $PROD_GOOGLE_MAPS_KEY
    VUE_APP_GOOGLE_ANALYTICS_4_KEY: $PROD_GOOGLE_ANALYTICS_4_KEY
    VUE_APP_GOOGLE_ANALYTICS_SECRET_CODE: $PROD_GOOGLE_ANALYTICS_SECRET_CODE
    VUE_APP_FIREBASE_CONFIG: $PROD_VUE_APP_FIREBASE_CONFIG
    VUE_APP_STATS_API: $PROD_VUE_APP_STATS_API
    VUE_APP_PIXEL_API: $PROD_VUE_APP_PIXEL_API
    VUE_APP_SHOW_CUSTOM_ADS: $PROD_VUE_APP_SHOW_CUSTOM_ADS
    VUE_APP_OUEDKNISS_CDN: $PROD_CDN_URL
    VUE_APP_ASSETS_PUBLIC_PATH: $PROD_VUE_APP_ASSETS_PUBLIC_PATH
    VUE_APP_OKAPTCHA_API: $PROD_VUE_APP_OKAPTCHA_API
    IMAGE_TAG: $CI_COMMIT_REF_NAME-dz
    NODE_ENV: production
  only:
    - master
  tags:
    - k8s_prod
    - prod
 
prod:dz2:build:
  extends: .build
  resource_group: production:dz2
  variables:
    VUE_APP_BRANCH_NAME: ""
    VUE_APP_GRAPHQL_HTTP: $PROD_VUE_APP_GRAPHQL_HTTP
    VUE_APP_SOCKET_IO: $PROD_DZ2_VUE_APP_SOCKET_IO
    VUE_APP_UPLOAD: $PROD_VUE_APP_STORAGE_URL
    VUE_APP_OUEDKNISS_AUTH: $PROD_DZ2_VUE_APP_OUEDKNISS_AUTH
    VUE_APP_OUEDKNISS_INTEL: $PROD_DZ2_VUE_APP_OUEDKNISS_INTEL
    VUE_APP_OUEDKNISS_PANEL: $PROD_DZ2_VUE_APP_OUEDKNISS_PANEL
    VUE_APP_OUEDKNISS_PORTAL: $PROD_DZ2_VUE_APP_OUEDKNISS_PORTAL
    VUE_APP_OUEDKNISS_STORE: $PROD_DZ2_VUE_APP_OUEDKNISS_STORE
    VUE_APP_OUEDKNISS_MARKET: $PROD_DZ2_VUE_APP_OUEDKNISS_MARKET
    VUE_APP_OUEDKNISS_DJEZZY: $PROD_DZ2_VUE_APP_OUEDKNISS_DJEZZY
    VUE_APP_RECAPTCHA_KEY: $PROD_VUE_APP_RECAPTCHA_KEY
    VUE_APP_INVISIBLE_RECAPTCHA_KEY: $PROD_VUE_APP_RECAPTCHA_INVISIBLE_KEY
    VUE_APP_DISABLE_MESSENGER: $PROD_VUE_APP_DISABLE_MESSENGER
    VUE_APP_DISABLE_OKPIXEL: $PROD_VUE_APP_DISABLE_OKPIXEL
    VUE_APP_GOOGLE_MAPS_KEY: $PROD_GOOGLE_MAPS_KEY
    VUE_APP_GOOGLE_ANALYTICS_4_KEY: $PROD_GOOGLE_ANALYTICS_4_KEY
    VUE_APP_GOOGLE_ANALYTICS_SECRET_CODE: $PROD_GOOGLE_ANALYTICS_SECRET_CODE
    VUE_APP_FIREBASE_CONFIG: $PROD_VUE_APP_FIREBASE_CONFIG
    VUE_APP_STATS_API: $PROD_VUE_APP_STATS_API
    VUE_APP_PIXEL_API: $PROD_VUE_APP_PIXEL_API
    VUE_APP_SHOW_CUSTOM_ADS: $PROD_VUE_APP_SHOW_CUSTOM_ADS
    VUE_APP_OUEDKNISS_CDN: $PROD_CDN_URL
    VUE_APP_ASSETS_PUBLIC_PATH: $PROD_VUE_APP_ASSETS_PUBLIC_PATH
    VUE_APP_OKAPTCHA_API: $PROD_VUE_APP_OKAPTCHA_API
    IMAGE_TAG: $CI_COMMIT_REF_NAME-dz2
    NODE_ENV: production
  only:
    - master
  tags:
    - k8s_prod
    - prod
